name: Publish

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Install Dependencies
        run: |
          cd website
          yarn

      - name: Publish
        run: GIT_USER=apollosadmin yarn publish-gh-pages
