name: Publish

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Install Dependencies
        run: yarn
        working-directory: website

      - name: Publish
        run: |
            git config --global user.email "apollosadmin@users.noreply.github.com"
            git config --global user.name "Apollos"
            echo "machine github.com login apollosadmin password ${{ secrets.PUBLISH_TOKEN }}" > ~/.netrc
            GIT_USER=apollosadmin yarn run publish-gh-pages
        working-directory: website
